"""Layer-agnostic knowledge-graph service: evidence → candidate → gate → active.

中央共享服务，L2 与 L3 各自的 pipeline 复用同一套证据/候选/门禁/晋级写入机制，
从而保证「同一个 database 文件」的统一数据链路。L2/L3 的*流程编排*仍各自保留在
``engine/industry/`` 与 ``engine/brand/``（方案 §3.2：不共用主题流程），但
数据落地的机械操作在这里集中，避免重复。

数据链路（方案 §3.0 / §9 / §10）：
    documents → evidence_spans → evidence_units → knowledge_candidates
    → gate_candidate_entities / gate_candidate_knowledge → (L1 门禁) → active graph
"""
from __future__ import annotations

import hashlib
from typing import Any

from engine.core.db import DB


# ---------------------------------------------------------------------------
# 溯源字段：所有候选都必须带 document 级溯源，文章撤稿/更新时可追踪
# ---------------------------------------------------------------------------

def document_provenance(db: DB, document_uuid: Any) -> dict[str, Any]:
    """Return {layer, published_at, original_url, content_hash} for a document."""
    rows = db.query(
        "SELECT layer, published_at, original_url, content_hash, title, status "
        "FROM document WHERE id = %s",
        (document_uuid,),
    )
    row = rows[0] if rows else {}
    return {
        "layer": row.get("layer"),
        "published_at": row.get("published_at"),
        "original_url": row.get("original_url"),
        "content_hash": row.get("content_hash"),
        "title": row.get("title"),
    }


def register_document(db: DB, row: dict, key_field: str = "document_id") -> str:
    """Upsert a document row (evidence-layer §9.1 `documents`) and return its UUID.

    ``row`` must contain ``document_id`` (business key); the ``id`` UUID column is
    auto-generated by the DB. Returns the row UUID so downstream tables can FK it.
    """
    existing = db.query(
        "SELECT id FROM document WHERE document_id = %s", (row.get("document_id"),)
    )
    if existing:
        doc_uuid = existing[0]["id"]
        # refresh provenance fields if changed (content_hash / title / status)
        db.execute(
            "UPDATE document SET published_at=COALESCE(%s, published_at), "
            "original_url=COALESCE(%s, original_url), "
            "content_hash=COALESCE(%s, content_hash), "
            "layer=COALESCE(%s, layer), "
            "title=COALESCE(%s, title), status=COALESCE(%s, status) WHERE id=%s",
            (
                row.get("published_at"), row.get("original_url"),
                row.get("content_hash"), row.get("layer"),
                row.get("title"), row.get("status"), doc_uuid,
            ),
        )
        return doc_uuid
    doc_uuid = db.insert_returning_id(
        "INSERT INTO document "
        "(id, document_id, tenant_id, layer, title, canonical_url, original_url, "
        " published_at, content_hash, source_status, status, mime_type, language) "
        "VALUES (uuid_generate_v4(), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) "
        "RETURNING id",
        (
            row.get("document_id"), row.get("tenant_id"), row.get("layer"),
            row.get("title"), row.get("canonical_url"), row.get("original_url"),
            row.get("published_at"), row.get("content_hash"),
            row.get("source_status") or "active", row.get("status") or "active",
            row.get("mime_type"), row.get("language"),
        ),
    )
    return doc_uuid


def upsert_evidence_span(db: DB, row: dict) -> None:
    """Upsert one evidence_span (span_id PK)."""
    span = {
        "span_id": row["span_id"],
        "document_id": row["document_uuid"],
        "span_type": row.get("span_type", "paragraph"),
        "text": row.get("text", ""),
        "heading_path": row.get("heading_path", []),
        "order_index": row.get("order_index", 0),
        "locator": row.get("locator"),
        "char_start": row.get("char_start"),
        "char_end": row.get("char_end"),
    }
    db.upsert("evidence_spans", span, "span_id")


def upsert_evidence_unit(db: DB, row: dict) -> None:
    """Upsert one evidence_unit (unit_id PK)."""
    unit = {
        "unit_id": row["unit_id"],
        "document_id": row["document_uuid"],
        "source_span_ids": row.get("source_span_ids", []),
        "text": row.get("text", ""),
        "heading_path": row.get("heading_path", []),
        "merge_reason": row.get("merge_reason", []),
        "token_count": row.get("token_count", 0),
    }
    db.upsert("evidence_units", unit, "unit_id")


def upsert_knowledge_candidate(db: DB, row: dict) -> str:
    """Upsert one document-level candidate into `knowledge_candidates` (§9.2).

    Returns the candidate_id. ``row`` must carry the provenance fields
    (document_id / published_at / original_url / content_hash) plus evidence_text.
    """
    cand = {
        "candidate_id": row["candidate_id"],
        "profile_id": row["profile_id"],
        "layer": row["layer"],
        "document_id": row["document_uuid"],
        "evidence_unit_id": row.get("evidence_unit_id"),
        "source_span_ids": row.get("source_span_ids", []),
        "candidate_type": row.get("candidate_type"),
        "subject": row.get("subject", {}),
        "predicate": row.get("predicate"),
        "object": row.get("object"),
        "metric": row.get("metric"),
        "statement": row.get("statement"),
        "event": row.get("event"),
        "evidence_text": row.get("evidence_text", ""),
        "confidence": row.get("confidence", 0.0),
        "extraction_method": row.get("extraction_method", []),
        # 溯源字段
        "schema_valid": row.get("schema_valid", True),
        "source_status": row.get("source_status"),
        "published_at": row.get("published_at"),
        "original_url": row.get("original_url"),
        "content_hash": row.get("content_hash"),
    }
    db.upsert("knowledge_candidates", cand, "candidate_id")
    return cand["candidate_id"]


# ---------------------------------------------------------------------------
# 跨文档融合输出 → 门禁候选（§9.3）
# ---------------------------------------------------------------------------

def upsert_gate_entity(db: DB, row: dict, key_field: str | None = None) -> str:
    """Upsert a fused gate-candidate entity; returns its entity_id (business key)."""
    entity_id = row["entity_id"]
    existing = db.query(
        "SELECT entity_type FROM gate_candidate_entities WHERE entity_id = %s",
        (entity_id,),
    )
    if existing:
        db.execute(
            "UPDATE gate_candidate_entities SET "
            "  name=%s, entity_type=%s, aliases=%s, description=%s, "
            "  source_candidate_ids=%s, evidence_refs=%s, "
            "  confidence=GREATEST(confidence, %s), embedding_id=COALESCE(%s, embedding_id) "
            "WHERE entity_id=%s",
            (
                row.get("name"), row.get("entity_type"), row.get("aliases", []),
                row.get("description"), row.get("source_candidate_ids", []),
                row.get("evidence_refs", []), row.get("confidence", 0.0),
                row.get("embedding_id"), entity_id,
            ),
        )
        return entity_id
    db.execute(
        "INSERT INTO gate_candidate_entities "
        "(entity_id, profile_id, layer, tenant_id, entity_type, name, aliases, "
        " description, source_candidate_ids, evidence_refs, confidence, embedding_id) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
        (
            entity_id, row.get("profile_id"), row.get("layer"), row.get("tenant_id"),
            row.get("entity_type"), row.get("name"), row.get("aliases", []),
            row.get("description"), row.get("source_candidate_ids", []),
            row.get("evidence_refs", []), row.get("confidence", 0.0),
            row.get("embedding_id"),
        ),
    )
    return entity_id


def upsert_gate_knowledge(db: DB, row: dict) -> str:
    """Upsert a fused gate-candidate knowledge row; returns knowledge_id."""
    entry = {
        "knowledge_id": row["knowledge_id"],
        "profile_id": row["profile_id"],
        "layer": row["layer"],
        "tenant_id": row.get("tenant_id"),
        "knowledge_type": row.get("knowledge_type"),
        "subject_entity_id": row.get("subject_entity_id"),
        "predicate_type": row.get("predicate_type"),
        "object_entity_id": row.get("object_entity_id"),
        "statement_text": row.get("statement_text"),
        "metric_name": row.get("metric_name"),
        "metric_value": row.get("metric_value"),
        "event": row.get("event"),
        "scope": row.get("scope", {}),
        "time_scope": row.get("time_scope", {}),
        "evidence_refs": row.get("evidence_refs", []),
        "source_candidate_ids": row.get("source_candidate_ids", []),
        "source_document_ids": row.get("source_document_ids", []),
        "latest_published_at": row.get("latest_published_at"),
        "confidence": row.get("confidence", 0.0),
        "embedding_id": row.get("embedding_id"),
        # schema 校验标记（High #7）：落库显式赋值，promotion 据此放行 gate_schema
        "schema_valid": bool(row.get("schema_valid", False)),
        "gate_status": row.get("gate_status", "pending"),
    }
    db.upsert("gate_candidate_knowledge", entry, "knowledge_id")
    return entry["knowledge_id"]


def pending_gate_candidates(
    db: DB, profile_id: str | None = None, knowledge_type: str | None = None
) -> list[dict]:
    """Fetch gate_candidate_knowledge rows still awaiting L1 gating."""
    where = ["gate_status = 'pending'"]
    params: list[Any] = []
    if profile_id:
        where.append("profile_id = %s")
        params.append(profile_id)
    if knowledge_type:
        where.append("knowledge_type = %s")
        params.append(knowledge_type)
    rows = db.query(
        "SELECT * FROM gate_candidate_knowledge WHERE " + " AND ".join(where)
        + " ORDER BY created_at",
        tuple(params),
    )
    return rows


def resolve_gate_entity(db: DB, profile_id: str, entity_id: str) -> dict:
    """Return a gate-candidate entity dict, or {} if not found."""
    rows = db.query(
        "SELECT * FROM gate_candidate_entities WHERE entity_id = %s AND profile_id = %s",
        (entity_id, profile_id),
    )
    return rows[0] if rows else {}


# ---------------------------------------------------------------------------
# 稳定主键/哈希工具
# ---------------------------------------------------------------------------

def stable_hash(*parts: Any) -> str:
    """Deterministic short hash for building stable candidate/knowledge ids."""
    raw = "::".join("" if p is None else str(p) for p in parts)
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


if __name__ == "__main__":
    print("knowledge_service ok")